pipeline:
    restore:
        image: microsoft/dotnet:2.1-sdk
        commands:
            - dotnet restore Photoblog.Api.csproj
    compile:
        image: microsoft/dotnet:2.1-sdk
        commands:
            - dotnet build Photoblog.Api.csproj
    publish:
        image: plugins/docker
        repo: tiagodeliberali/photoblog_back
        tags: latest
        secrets: [ docker_username, docker_password ]